<a href="https://colab.research.google.com/github/23071234-coder/NNDL/blob/main/Prac1_NNDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#1. Vector addition
#Define two 1D array(vectors) of same shape
vec_a = np.array([1,2,3])
vec_b = np.array([4,5,6])
#Perform element-wise addition
vec_sum = vec_a + vec_b
print("-- Vector Addition --")
print("Vector A :",vec_a)
print("Vector B :",vec_b)
print("Sum(A+B) :",vec_sum)
print()

#2. Matrix Multiplication
#Define 2*3 matrix(matrix x) & a 3*2 matrix(matrix y)
matrix_x = np.array([[1,2,3],[4,5,6]])
matrix_y = np.array([[7,8],[9,10],[11,12]])
#Perform matrix multiplication
matrix_mul = np.dot(matrix_x,matrix_y)
print("-- Matrix Multiplication --")
print("Matrix X (2*3) :\n",matrix_x)
print("Matrix Y (3*2) :\n",matrix_y)
print("Matrix X (2*2) :\n",matrix_mul)

-- Vector Addition --
Vector A : [1 2 3]
Vector B : [4 5 6]
Sum(A+B) : [5 7 9]

-- Matrix Multiplication --
Matrix X (2*3) :
 [[1 2 3]
 [4 5 6]]
Matrix Y (3*2) :
 [[ 7  8]
 [ 9 10]
 [11 12]]
Matrix X (2*2) :
 [[ 58  64]
 [139 154]]
